// <auto-generated />
using System;
using AMSS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMSS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240518055911_ManyToManyRelationShipFieldCrop")]
    partial class ManyToManyRelationShipFieldCrop
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AMSS.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AMSS.Models.Crop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CareLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CropTypeId")
                        .HasColumnType("int");

                    b.Property<double>("CultivatedArea")
                        .HasColumnType("float");

                    b.Property<string>("Cycle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Edible")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ExpectedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GrowthRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HardinessZone")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("Indoor")
                        .HasColumnType("bit");

                    b.Property<string>("Maintenance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PlantedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Propogation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Soil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Watering")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CropTypeId");

                    b.ToTable("Crops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CareLevel = "Easy",
                            CreatedAt = new DateTime(2024, 4, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8204),
                            CropTypeId = 1,
                            CultivatedArea = 891.0,
                            Cycle = "Annual",
                            Description = "High-yielding rice variety suitable for wetland cultivation.",
                            Edible = true,
                            ExpectedDate = new DateTime(2024, 8, 16, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8202),
                            GrowthRate = "Fast",
                            HardinessZone = 8,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Rice.jpg",
                            Indoor = false,
                            Maintenance = "Low",
                            Name = "Rice Crop 1",
                            PlantedDate = new DateTime(2024, 4, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8200),
                            Propogation = "Seed",
                            Quantity = 500,
                            Soil = "Clay",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8206),
                            Watering = "Heavy"
                        },
                        new
                        {
                            Id = 2,
                            CareLevel = "Easy",
                            CreatedAt = new DateTime(2024, 4, 3, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8211),
                            CropTypeId = 1,
                            CultivatedArea = 900.20000000000005,
                            Cycle = "Annual",
                            Description = "High-yielding rice variety suitable for wetland cultivation.",
                            Edible = true,
                            ExpectedDate = new DateTime(2024, 8, 21, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8210),
                            GrowthRate = "Fast",
                            HardinessZone = 8,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Rice.jpg",
                            Indoor = false,
                            Maintenance = "Low",
                            Name = "Rice Crop 2",
                            PlantedDate = new DateTime(2024, 4, 3, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8210),
                            Propogation = "Seed",
                            Quantity = 400,
                            Soil = "Clay",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8212),
                            Watering = "Heavy"
                        },
                        new
                        {
                            Id = 3,
                            CareLevel = "Moderate",
                            CreatedAt = new DateTime(2024, 4, 28, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8217),
                            CropTypeId = 2,
                            CultivatedArea = 667.70000000000005,
                            Cycle = "Annual",
                            Description = "Maize crop known for its versatility and use in various food products.",
                            Edible = true,
                            ExpectedDate = new DateTime(2024, 8, 26, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8216),
                            GrowthRate = "Medium",
                            HardinessZone = 9,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Corn.jpg",
                            Indoor = false,
                            Maintenance = "Medium",
                            Name = "Corn Crop 1",
                            PlantedDate = new DateTime(2024, 4, 28, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8215),
                            Propogation = "Seed",
                            Quantity = 700,
                            Soil = "Loam",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8218),
                            Watering = "Moderate"
                        },
                        new
                        {
                            Id = 4,
                            CareLevel = "Moderate",
                            CreatedAt = new DateTime(2024, 4, 13, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8222),
                            CropTypeId = 2,
                            CultivatedArea = 292.30000000000001,
                            Cycle = "Annual",
                            Description = "Maize crop known for its versatility and use in various food products.",
                            Edible = true,
                            ExpectedDate = new DateTime(2024, 8, 31, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8221),
                            GrowthRate = "Medium",
                            HardinessZone = 9,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Corn.jpg",
                            Indoor = false,
                            Maintenance = "Medium",
                            Name = "Corn Crop 2",
                            PlantedDate = new DateTime(2024, 4, 13, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8221),
                            Propogation = "Seed",
                            Quantity = 600,
                            Soil = "Loam",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8223),
                            Watering = "Moderate"
                        },
                        new
                        {
                            Id = 5,
                            CareLevel = "Moderate",
                            CreatedAt = new DateTime(2024, 5, 8, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8227),
                            CropTypeId = 5,
                            CultivatedArea = 729.39999999999998,
                            Cycle = "Annual",
                            Description = "Starchy tuberous crop widely consumed as a staple food.",
                            Edible = true,
                            ExpectedDate = new DateTime(2024, 9, 25, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8226),
                            GrowthRate = "Fast",
                            HardinessZone = 8,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Potato.jpg",
                            Indoor = false,
                            Maintenance = "Medium",
                            Name = "Potato Crop 1",
                            PlantedDate = new DateTime(2024, 5, 8, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8226),
                            Propogation = "Tuber",
                            Quantity = 1000,
                            Soil = "Sandy Loam",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8228),
                            Watering = "Moderate"
                        },
                        new
                        {
                            Id = 6,
                            CareLevel = "Moderate",
                            CreatedAt = new DateTime(2024, 4, 23, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8233),
                            CropTypeId = 5,
                            CultivatedArea = 834.0,
                            Cycle = "Annual",
                            Description = "Starchy tuberous crop widely consumed as a staple food.",
                            Edible = true,
                            ExpectedDate = new DateTime(2024, 9, 30, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8232),
                            GrowthRate = "Fast",
                            HardinessZone = 8,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Potato.jpg",
                            Indoor = false,
                            Maintenance = "Medium",
                            Name = "Potato Crop 2",
                            PlantedDate = new DateTime(2024, 4, 23, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8231),
                            Propogation = "Tuber",
                            Quantity = 900,
                            Soil = "Sandy Loam",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8233),
                            Watering = "Moderate"
                        },
                        new
                        {
                            Id = 7,
                            CareLevel = "Moderate",
                            CreatedAt = new DateTime(2024, 5, 13, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8239),
                            CropTypeId = 6,
                            CultivatedArea = 662.39999999999998,
                            Cycle = "Annual",
                            Description = "Versatile crop used in various culinary dishes and sauces, rich in vitamins and minerals.",
                            Edible = true,
                            ExpectedDate = new DateTime(2024, 10, 5, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8238),
                            GrowthRate = "Fast",
                            HardinessZone = 9,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Tomato.jpg",
                            Indoor = false,
                            Maintenance = "Medium",
                            Name = "Tomato Crop 1",
                            PlantedDate = new DateTime(2024, 5, 13, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8237),
                            Propogation = "Seed",
                            Quantity = 1100,
                            Soil = "Loamy",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8240),
                            Watering = "Moderate"
                        },
                        new
                        {
                            Id = 8,
                            CareLevel = "Moderate",
                            CreatedAt = new DateTime(2024, 4, 28, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8244),
                            CropTypeId = 6,
                            CultivatedArea = 389.0,
                            Cycle = "Annual",
                            Description = "Versatile crop used in various culinary dishes and sauces, rich in vitamins and minerals.",
                            Edible = true,
                            ExpectedDate = new DateTime(2024, 10, 10, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8243),
                            GrowthRate = "Fast",
                            HardinessZone = 9,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Tomato.jpg",
                            Indoor = false,
                            Maintenance = "Medium",
                            Name = "Tomato Crop 2",
                            PlantedDate = new DateTime(2024, 4, 28, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8243),
                            Propogation = "Seed",
                            Quantity = 1000,
                            Soil = "Loamy",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8245),
                            Watering = "Moderate"
                        },
                        new
                        {
                            Id = 9,
                            CareLevel = "Difficult",
                            CreatedAt = new DateTime(2024, 5, 13, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8249),
                            CropTypeId = 7,
                            CultivatedArea = 732.10000000000002,
                            Cycle = "Perennial",
                            Description = "Popular fruit crop known for its crisp texture and sweet flavor, cultivated in orchards worldwide.",
                            Edible = true,
                            ExpectedDate = new DateTime(2024, 10, 15, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8248),
                            GrowthRate = "Medium",
                            HardinessZone = 5,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Apple.jpg",
                            Indoor = false,
                            Maintenance = "High",
                            Name = "Apple Crop 1",
                            PlantedDate = new DateTime(2024, 5, 13, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8248),
                            Propogation = "Seed",
                            Quantity = 1200,
                            Soil = "Loamy",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8250),
                            Watering = "Moderate"
                        },
                        new
                        {
                            Id = 10,
                            CareLevel = "Difficult",
                            CreatedAt = new DateTime(2024, 5, 8, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8255),
                            CropTypeId = 7,
                            CultivatedArea = 424.60000000000002,
                            Cycle = "Perennial",
                            Description = "Popular fruit crop known for its crisp texture and sweet flavor, cultivated in orchards worldwide.",
                            Edible = true,
                            ExpectedDate = new DateTime(2024, 10, 20, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8254),
                            GrowthRate = "Medium",
                            HardinessZone = 5,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Apple.jpg",
                            Indoor = false,
                            Maintenance = "High",
                            Name = "Apple Crop 2",
                            PlantedDate = new DateTime(2024, 5, 8, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8253),
                            Propogation = "Seed",
                            Quantity = 1100,
                            Soil = "Loamy",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8255),
                            Watering = "Moderate"
                        },
                        new
                        {
                            Id = 11,
                            CareLevel = "Moderate",
                            CreatedAt = new DateTime(2024, 5, 8, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8260),
                            CropTypeId = 8,
                            CultivatedArea = 293.39999999999998,
                            Cycle = "Perennial",
                            Description = "Tropical fruit crop with high nutritional value, grown in warm climates and consumed worldwide.",
                            Edible = true,
                            ExpectedDate = new DateTime(2024, 10, 25, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8259),
                            GrowthRate = "Fast",
                            HardinessZone = 10,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Banana.jpg",
                            Indoor = false,
                            Maintenance = "High",
                            Name = "Banana Crop 1",
                            PlantedDate = new DateTime(2024, 5, 8, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8258),
                            Propogation = "Sucker",
                            Quantity = 1300,
                            Soil = "Loamy",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8260),
                            Watering = "Heavy"
                        },
                        new
                        {
                            Id = 12,
                            CareLevel = "Moderate",
                            CreatedAt = new DateTime(2024, 5, 13, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8265),
                            CropTypeId = 8,
                            CultivatedArea = 444.5,
                            Cycle = "Perennial",
                            Description = "Tropical fruit crop with high nutritional value, grown in warm climates and consumed worldwide.",
                            Edible = true,
                            ExpectedDate = new DateTime(2024, 10, 30, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8264),
                            GrowthRate = "Fast",
                            HardinessZone = 10,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Banana.jpg",
                            Indoor = false,
                            Maintenance = "High",
                            Name = "Banana Crop 2",
                            PlantedDate = new DateTime(2024, 5, 13, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8263),
                            Propogation = "Sucker",
                            Quantity = 1200,
                            Soil = "Loamy",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8266),
                            Watering = "Heavy"
                        },
                        new
                        {
                            Id = 13,
                            CareLevel = "Moderate",
                            CreatedAt = new DateTime(2024, 5, 23, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8270),
                            CropTypeId = 9,
                            CultivatedArea = 596.70000000000005,
                            Cycle = "Perennial",
                            Description = "Citrus fruit crop prized for its tangy flavor and high vitamin C content.",
                            Edible = true,
                            ExpectedDate = new DateTime(2024, 11, 4, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8269),
                            GrowthRate = "Medium",
                            HardinessZone = 9,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Orange.jpg",
                            Indoor = false,
                            Maintenance = "High",
                            Name = "Orange Crop 1",
                            PlantedDate = new DateTime(2024, 5, 23, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8269),
                            Propogation = "Seed",
                            Quantity = 1400,
                            Soil = "Sandy Loam",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8271),
                            Watering = "Moderate"
                        },
                        new
                        {
                            Id = 14,
                            CareLevel = "Moderate",
                            CreatedAt = new DateTime(2024, 5, 8, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8275),
                            CropTypeId = 9,
                            CultivatedArea = 821.10000000000002,
                            Cycle = "Perennial",
                            Description = "Citrus fruit crop prized for its tangy flavor and high vitamin C content.",
                            Edible = true,
                            ExpectedDate = new DateTime(2024, 11, 9, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8274),
                            GrowthRate = "Medium",
                            HardinessZone = 9,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Orange.jpg",
                            Indoor = false,
                            Maintenance = "High",
                            Name = "Orange Crop 2",
                            PlantedDate = new DateTime(2024, 5, 8, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8274),
                            Propogation = "Seed",
                            Quantity = 1300,
                            Soil = "Sandy Loam",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8276),
                            Watering = "Moderate"
                        },
                        new
                        {
                            Id = 15,
                            CareLevel = "Easy",
                            CreatedAt = new DateTime(2024, 6, 2, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8281),
                            CropTypeId = 10,
                            CultivatedArea = 513.29999999999995,
                            Cycle = "Annual",
                            Description = "Staple grain crop known for its high carbohydrate content, used in various food products.",
                            Edible = true,
                            ExpectedDate = new DateTime(2024, 11, 14, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8280),
                            GrowthRate = "Fast",
                            HardinessZone = 8,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Wheat.jpg",
                            Indoor = false,
                            Maintenance = "Low",
                            Name = "Wheat Crop 1",
                            PlantedDate = new DateTime(2024, 6, 2, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8279),
                            Propogation = "Seed",
                            Quantity = 1500,
                            Soil = "Loamy",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8281),
                            Watering = "Moderate"
                        },
                        new
                        {
                            Id = 16,
                            CareLevel = "Easy",
                            CreatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8286),
                            CropTypeId = 10,
                            CultivatedArea = 624.70000000000005,
                            Cycle = "Annual",
                            Description = "Staple grain crop known for its high carbohydrate content, used in various food products.",
                            Edible = true,
                            ExpectedDate = new DateTime(2024, 11, 19, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8285),
                            GrowthRate = "Fast",
                            HardinessZone = 8,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Wheat.jpg",
                            Indoor = false,
                            Maintenance = "Low",
                            Name = "Wheat Crop 2",
                            PlantedDate = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8284),
                            Propogation = "Seed",
                            Quantity = 1400,
                            Soil = "Loamy",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8287),
                            Watering = "Moderate"
                        },
                        new
                        {
                            Id = 17,
                            CareLevel = "Easy",
                            CreatedAt = new DateTime(2024, 5, 3, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8291),
                            CropTypeId = 11,
                            CultivatedArea = 342.60000000000002,
                            Cycle = "Annual",
                            Description = "Grain crop valued for its use in food, beverages, and animal feed.",
                            Edible = true,
                            ExpectedDate = new DateTime(2024, 11, 24, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8290),
                            GrowthRate = "Fast",
                            HardinessZone = 8,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Barley.jpg",
                            Indoor = false,
                            Maintenance = "Low",
                            Name = "Barley Crop 1",
                            PlantedDate = new DateTime(2024, 5, 3, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8290),
                            Propogation = "Seed",
                            Quantity = 1600,
                            Soil = "Loamy",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8292),
                            Watering = "Moderate"
                        },
                        new
                        {
                            Id = 18,
                            CareLevel = "Easy",
                            CreatedAt = new DateTime(2024, 4, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8297),
                            CropTypeId = 11,
                            CultivatedArea = 732.89999999999998,
                            Cycle = "Annual",
                            Description = "Grain crop valued for its use in food, beverages, and animal feed.",
                            Edible = true,
                            ExpectedDate = new DateTime(2024, 11, 29, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8295),
                            GrowthRate = "Fast",
                            HardinessZone = 8,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Barley.jpg",
                            Indoor = false,
                            Maintenance = "Low",
                            Name = "Barley Crop 2",
                            PlantedDate = new DateTime(2024, 4, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8295),
                            Propogation = "Seed",
                            Quantity = 1500,
                            Soil = "Loamy",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8298),
                            Watering = "Moderate"
                        },
                        new
                        {
                            Id = 19,
                            CareLevel = "Easy",
                            CreatedAt = new DateTime(2024, 4, 3, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8302),
                            CropTypeId = 12,
                            CultivatedArea = 921.79999999999995,
                            Cycle = "Annual",
                            Description = "Legume crop rich in protein, widely used in food products and animal feed.",
                            Edible = true,
                            ExpectedDate = new DateTime(2024, 12, 4, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8301),
                            GrowthRate = "Medium",
                            HardinessZone = 8,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Soybean.jpg",
                            Indoor = false,
                            Maintenance = "Low",
                            Name = "Soybean Crop 1",
                            PlantedDate = new DateTime(2024, 4, 3, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8301),
                            Propogation = "Seed",
                            Quantity = 1700,
                            Soil = "Loamy",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8303),
                            Watering = "Moderate"
                        },
                        new
                        {
                            Id = 20,
                            CareLevel = "Easy",
                            CreatedAt = new DateTime(2024, 3, 19, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8308),
                            CropTypeId = 12,
                            CultivatedArea = 623.39999999999998,
                            Cycle = "Annual",
                            Description = "Legume crop rich in protein, widely used in food products and animal feed.",
                            Edible = true,
                            ExpectedDate = new DateTime(2024, 12, 9, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8308),
                            GrowthRate = "Medium",
                            HardinessZone = 8,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Soybean.jpg",
                            Indoor = false,
                            Maintenance = "Low",
                            Name = "Soybean Crop 2",
                            PlantedDate = new DateTime(2024, 3, 19, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8307),
                            Propogation = "Seed",
                            Quantity = 1600,
                            Soil = "Loamy",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8309),
                            Watering = "Moderate"
                        },
                        new
                        {
                            Id = 21,
                            CareLevel = "Easy",
                            CreatedAt = new DateTime(2024, 4, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8314),
                            CropTypeId = 13,
                            CultivatedArea = 545.10000000000002,
                            Cycle = "Annual",
                            Description = "Versatile crop used for food, fodder, and biofuel production.",
                            Edible = true,
                            ExpectedDate = new DateTime(2024, 12, 14, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8313),
                            GrowthRate = "Medium",
                            HardinessZone = 9,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Sorghum.jpg",
                            Indoor = false,
                            Maintenance = "Low",
                            Name = "Sorghum Crop 1",
                            PlantedDate = new DateTime(2024, 4, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8312),
                            Propogation = "Seed",
                            Quantity = 1800,
                            Soil = "Sandy Loam",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8314),
                            Watering = "Moderate"
                        },
                        new
                        {
                            Id = 22,
                            CareLevel = "Easy",
                            CreatedAt = new DateTime(2024, 4, 3, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8319),
                            CropTypeId = 13,
                            CultivatedArea = 721.29999999999995,
                            Cycle = "Annual",
                            Description = "Versatile crop used for food, fodder, and biofuel production.",
                            Edible = true,
                            ExpectedDate = new DateTime(2024, 12, 19, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8318),
                            GrowthRate = "Medium",
                            HardinessZone = 9,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Sorghum.jpg",
                            Indoor = false,
                            Maintenance = "Low",
                            Name = "Sorghum Crop 2",
                            PlantedDate = new DateTime(2024, 4, 3, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8317),
                            Propogation = "Seed",
                            Quantity = 1700,
                            Soil = "Sandy Loam",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8319),
                            Watering = "Moderate"
                        },
                        new
                        {
                            Id = 23,
                            CareLevel = "Easy",
                            CreatedAt = new DateTime(2024, 3, 19, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8324),
                            CropTypeId = 14,
                            CultivatedArea = 564.70000000000005,
                            Cycle = "Annual",
                            Description = "Cereal grain known for its high nutritional value, often used in breakfast foods and animal feed.",
                            Edible = true,
                            ExpectedDate = new DateTime(2024, 12, 24, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8323),
                            GrowthRate = "Fast",
                            HardinessZone = 7,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Oats.jpg",
                            Indoor = false,
                            Maintenance = "Low",
                            Name = "Oats Crop 1",
                            PlantedDate = new DateTime(2024, 3, 19, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8322),
                            Propogation = "Seed",
                            Quantity = 1900,
                            Soil = "Loamy",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8325),
                            Watering = "Moderate"
                        },
                        new
                        {
                            Id = 24,
                            CareLevel = "Easy",
                            CreatedAt = new DateTime(2024, 3, 4, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8330),
                            CropTypeId = 14,
                            CultivatedArea = 633.20000000000005,
                            Cycle = "Annual",
                            Description = "Cereal grain known for its high nutritional value, often used in breakfast foods and animal feed.",
                            Edible = true,
                            ExpectedDate = new DateTime(2024, 12, 29, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8329),
                            GrowthRate = "Fast",
                            HardinessZone = 7,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Oats.jpg",
                            Indoor = false,
                            Maintenance = "Low",
                            Name = "Oats Crop 2",
                            PlantedDate = new DateTime(2024, 3, 4, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8329),
                            Propogation = "Seed",
                            Quantity = 1800,
                            Soil = "Loamy",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8331),
                            Watering = "Moderate"
                        },
                        new
                        {
                            Id = 25,
                            CareLevel = "Easy",
                            CreatedAt = new DateTime(2024, 4, 23, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8335),
                            CropTypeId = 1,
                            CultivatedArea = 712.60000000000002,
                            Cycle = "Annual",
                            Description = "High-yielding rice variety suitable for wetland cultivation.",
                            Edible = true,
                            ExpectedDate = new DateTime(2025, 1, 3, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8334),
                            GrowthRate = "Fast",
                            HardinessZone = 8,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Rice.jpg",
                            Indoor = false,
                            Maintenance = "Low",
                            Name = "Rice Crop 3",
                            PlantedDate = new DateTime(2024, 4, 23, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8334),
                            Propogation = "Seed",
                            Quantity = 2000,
                            Soil = "Clay",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8336),
                            Watering = "Heavy"
                        },
                        new
                        {
                            Id = 26,
                            CareLevel = "Easy",
                            CreatedAt = new DateTime(2024, 4, 8, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8341),
                            CropTypeId = 1,
                            CultivatedArea = 789.10000000000002,
                            Cycle = "Annual",
                            Description = "High-yielding rice variety suitable for wetland cultivation.",
                            Edible = true,
                            ExpectedDate = new DateTime(2025, 1, 8, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8340),
                            GrowthRate = "Fast",
                            HardinessZone = 8,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Rice.jpg",
                            Indoor = false,
                            Maintenance = "Low",
                            Name = "Rice Crop 4",
                            PlantedDate = new DateTime(2024, 4, 8, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8339),
                            Propogation = "Seed",
                            Quantity = 1900,
                            Soil = "Clay",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8342),
                            Watering = "Heavy"
                        },
                        new
                        {
                            Id = 27,
                            CareLevel = "Moderate",
                            CreatedAt = new DateTime(2024, 3, 24, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8346),
                            CropTypeId = 2,
                            CultivatedArea = 847.29999999999995,
                            Cycle = "Annual",
                            Description = "Maize crop known for its versatility and use in various food products.",
                            Edible = true,
                            ExpectedDate = new DateTime(2025, 1, 13, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8345),
                            GrowthRate = "Medium",
                            HardinessZone = 9,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Corn.jpg",
                            Indoor = false,
                            Maintenance = "Medium",
                            Name = "Corn Crop 3",
                            PlantedDate = new DateTime(2024, 3, 24, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8344),
                            Propogation = "Seed",
                            Quantity = 2100,
                            Soil = "Loam",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8347),
                            Watering = "Moderate"
                        },
                        new
                        {
                            Id = 28,
                            CareLevel = "Moderate",
                            CreatedAt = new DateTime(2024, 3, 9, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8352),
                            CropTypeId = 2,
                            CultivatedArea = 612.39999999999998,
                            Cycle = "Annual",
                            Description = "Maize crop known for its versatility and use in various food products.",
                            Edible = true,
                            ExpectedDate = new DateTime(2025, 1, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8352),
                            GrowthRate = "Medium",
                            HardinessZone = 9,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Corn.jpg",
                            Indoor = false,
                            Maintenance = "Medium",
                            Name = "Corn Crop 4",
                            PlantedDate = new DateTime(2024, 3, 9, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8350),
                            Propogation = "Seed",
                            Quantity = 2000,
                            Soil = "Loam",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8353),
                            Watering = "Moderate"
                        },
                        new
                        {
                            Id = 29,
                            CareLevel = "Moderate",
                            CreatedAt = new DateTime(2024, 2, 23, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8358),
                            CropTypeId = 5,
                            CultivatedArea = 445.80000000000001,
                            Cycle = "Annual",
                            Description = "Starchy tuberous crop widely consumed as a staple food.",
                            Edible = true,
                            ExpectedDate = new DateTime(2025, 1, 23, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8357),
                            GrowthRate = "Fast",
                            HardinessZone = 8,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Potato.jpg",
                            Indoor = false,
                            Maintenance = "Medium",
                            Name = "Potato Crop 3",
                            PlantedDate = new DateTime(2024, 2, 23, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8356),
                            Propogation = "Tuber",
                            Quantity = 2200,
                            Soil = "Sandy Loam",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8358),
                            Watering = "Moderate"
                        },
                        new
                        {
                            Id = 30,
                            CareLevel = "Moderate",
                            CreatedAt = new DateTime(2024, 2, 8, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8364),
                            CropTypeId = 5,
                            CultivatedArea = 832.10000000000002,
                            Cycle = "Annual",
                            Description = "Starchy tuberous crop widely consumed as a staple food.",
                            Edible = true,
                            ExpectedDate = new DateTime(2025, 1, 28, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8363),
                            GrowthRate = "Fast",
                            HardinessZone = 8,
                            Icon = "https://amssimages.blob.core.windows.net/agriculture/Potato.jpg",
                            Indoor = false,
                            Maintenance = "Medium",
                            Name = "Potato Crop 4",
                            PlantedDate = new DateTime(2024, 2, 8, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8362),
                            Propogation = "Tuber",
                            Quantity = 2100,
                            Soil = "Sandy Loam",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8364),
                            Watering = "Moderate"
                        });
                });

            modelBuilder.Entity("AMSS.Models.CropType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CropTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "RC",
                            CreatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8080),
                            Name = "Rice",
                            Type = "Cereal",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8083)
                        },
                        new
                        {
                            Id = 2,
                            Code = "CN",
                            CreatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8087),
                            Name = "Corn",
                            Type = "Cereal",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8087)
                        },
                        new
                        {
                            Id = 3,
                            Code = "SB",
                            CreatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8090),
                            Name = "Soybean",
                            Type = "Legume",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8090)
                        },
                        new
                        {
                            Id = 4,
                            Code = "SC",
                            CreatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8092),
                            Name = "Sugarcane",
                            Type = "Sugar Crop",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8092)
                        },
                        new
                        {
                            Id = 5,
                            Code = "PT",
                            CreatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8094),
                            Name = "Potato",
                            Type = "Tuber",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8094)
                        },
                        new
                        {
                            Id = 6,
                            Code = "TM",
                            CreatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8096),
                            Name = "Tomato",
                            Type = "Vegetable",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8096)
                        },
                        new
                        {
                            Id = 7,
                            Code = "AP",
                            CreatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8098),
                            Name = "Apple",
                            Type = "Fruit",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8098)
                        },
                        new
                        {
                            Id = 8,
                            Code = "BN",
                            CreatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8100),
                            Name = "Banana",
                            Type = "Fruit",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8100)
                        },
                        new
                        {
                            Id = 9,
                            Code = "OR",
                            CreatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8102),
                            Name = "Orange",
                            Type = "Fruit",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8102)
                        },
                        new
                        {
                            Id = 10,
                            Code = "GP",
                            CreatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8103),
                            Name = "Grapes",
                            Type = "Fruit",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8104)
                        },
                        new
                        {
                            Id = 11,
                            Code = "PL",
                            CreatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8105),
                            Name = "Pineapple",
                            Type = "Fruit",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8106)
                        },
                        new
                        {
                            Id = 12,
                            Code = "SBY",
                            CreatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8108),
                            Name = "Strawberry",
                            Type = "Fruit",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8108)
                        },
                        new
                        {
                            Id = 13,
                            Code = "CF",
                            CreatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8110),
                            Name = "Coffee",
                            Type = "Beverage Crop",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8110)
                        },
                        new
                        {
                            Id = 14,
                            Code = "TE",
                            CreatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8113),
                            Name = "Tea",
                            Type = "Beverage Crop",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8113)
                        },
                        new
                        {
                            Id = 15,
                            Code = "CC",
                            CreatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8115),
                            Name = "Cocoa",
                            Type = "Beverage Crop",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8115)
                        },
                        new
                        {
                            Id = 16,
                            Code = "PN",
                            CreatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8117),
                            Name = "Peanut",
                            Type = "Legume",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8117)
                        },
                        new
                        {
                            Id = 17,
                            Code = "CR",
                            CreatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8119),
                            Name = "Carrot",
                            Type = "Vegetable",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8119)
                        },
                        new
                        {
                            Id = 18,
                            Code = "BK",
                            CreatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8120),
                            Name = "Broccoli",
                            Type = "Vegetable",
                            UpdatedAt = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(8121)
                        });
                });

            modelBuilder.Entity("AMSS.Models.Farm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PolygonAppId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("PolygonAppId")
                        .IsUnique();

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("AMSS.Models.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FarmId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PolygonAppId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PolygonAppId")
                        .IsUnique();

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("AMSS.Models.FieldCrop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CropId");

                    b.HasIndex("FieldId");

                    b.ToTable("FieldCrops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CropId = 2,
                            FieldId = 3
                        },
                        new
                        {
                            Id = 2,
                            CropId = 1,
                            FieldId = 3
                        },
                        new
                        {
                            Id = 3,
                            CropId = 4,
                            FieldId = 3
                        },
                        new
                        {
                            Id = 4,
                            CropId = 3,
                            FieldId = 5
                        },
                        new
                        {
                            Id = 5,
                            CropId = 2,
                            FieldId = 5
                        },
                        new
                        {
                            Id = 6,
                            CropId = 5,
                            FieldId = 6
                        },
                        new
                        {
                            Id = 7,
                            CropId = 7,
                            FieldId = 6
                        },
                        new
                        {
                            Id = 8,
                            CropId = 6,
                            FieldId = 7
                        },
                        new
                        {
                            Id = 9,
                            CropId = 8,
                            FieldId = 7
                        },
                        new
                        {
                            Id = 10,
                            CropId = 9,
                            FieldId = 12
                        },
                        new
                        {
                            Id = 11,
                            CropId = 10,
                            FieldId = 8
                        },
                        new
                        {
                            Id = 12,
                            CropId = 9,
                            FieldId = 12
                        },
                        new
                        {
                            Id = 13,
                            CropId = 9,
                            FieldId = 8
                        });
                });

            modelBuilder.Entity("AMSS.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<float?>("Lat")
                        .HasColumnType("real");

                    b.Property<float?>("Lng")
                        .HasColumnType("real");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("AMSS.Models.Polygon.PolygonApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PolygonApps");
                });

            modelBuilder.Entity("AMSS.Models.Polygon.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Lat")
                        .HasColumnType("real");

                    b.Property<int?>("PolygonAppId")
                        .HasColumnType("int");

                    b.Property<float>("lng")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PolygonAppId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("AMSS.Models.SoilQuality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Chlorophyll")
                        .HasColumnType("real");

                    b.Property<int?>("FieldId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InfoTime")
                        .HasColumnType("datetime2");

                    b.Property<float>("Iron")
                        .HasColumnType("real");

                    b.Property<float>("Nitrate")
                        .HasColumnType("real");

                    b.Property<float>("Oxygen")
                        .HasColumnType("real");

                    b.Property<float>("PH")
                        .HasColumnType("real");

                    b.Property<float>("Phyto")
                        .HasColumnType("real");

                    b.Property<float>("Phytoplankton")
                        .HasColumnType("real");

                    b.Property<float>("Salinity")
                        .HasColumnType("real");

                    b.Property<float>("Silicate")
                        .HasColumnType("real");

                    b.Property<int>("SoilMoisture")
                        .HasColumnType("int");

                    b.Property<int>("SoilMoisture100cm")
                        .HasColumnType("int");

                    b.Property<int>("SoilMoisture10cm")
                        .HasColumnType("int");

                    b.Property<int>("SoilMoisture40cm")
                        .HasColumnType("int");

                    b.Property<int>("SoilTemperature")
                        .HasColumnType("int");

                    b.Property<int>("SoilTemperature100cm")
                        .HasColumnType("int");

                    b.Property<int>("SoilTemperature10cm")
                        .HasColumnType("int");

                    b.Property<int>("SoilTemperature40cm")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FieldId")
                        .IsUnique()
                        .HasFilter("[FieldId] IS NOT NULL");

                    b.ToTable("SoilQualitys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Chlorophyll = 0.1f,
                            FieldId = 3,
                            InfoTime = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(7821),
                            Iron = 0.2f,
                            Nitrate = 0.3f,
                            Oxygen = 0.5f,
                            PH = 7f,
                            Phyto = 0.4f,
                            Phytoplankton = 0.6f,
                            Salinity = 0.8f,
                            Silicate = 0.7f,
                            SoilMoisture = 50,
                            SoilMoisture100cm = 80,
                            SoilMoisture10cm = 60,
                            SoilMoisture40cm = 70,
                            SoilTemperature = 25,
                            SoilTemperature100cm = 28,
                            SoilTemperature10cm = 26,
                            SoilTemperature40cm = 27
                        },
                        new
                        {
                            Id = 2,
                            Chlorophyll = 0.2f,
                            FieldId = 5,
                            InfoTime = new DateTime(2024, 5, 18, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(7848),
                            Iron = 0.3f,
                            Nitrate = 0.4f,
                            Oxygen = 0.6f,
                            PH = 7.1f,
                            Phyto = 0.5f,
                            Phytoplankton = 0.7f,
                            Salinity = 0.9f,
                            Silicate = 0.8f,
                            SoilMoisture = 55,
                            SoilMoisture100cm = 85,
                            SoilMoisture10cm = 65,
                            SoilMoisture40cm = 75,
                            SoilTemperature = 26,
                            SoilTemperature100cm = 29,
                            SoilTemperature10cm = 27,
                            SoilTemperature40cm = 28
                        },
                        new
                        {
                            Id = 3,
                            Chlorophyll = 0.15f,
                            FieldId = 6,
                            InfoTime = new DateTime(2024, 5, 17, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(7852),
                            Iron = 0.25f,
                            Nitrate = 0.35f,
                            Oxygen = 0.55f,
                            PH = 7.2f,
                            Phyto = 0.45f,
                            Phytoplankton = 0.65f,
                            Salinity = 0.85f,
                            Silicate = 0.75f,
                            SoilMoisture = 52,
                            SoilMoisture100cm = 82,
                            SoilMoisture10cm = 62,
                            SoilMoisture40cm = 72,
                            SoilTemperature = 24,
                            SoilTemperature100cm = 27,
                            SoilTemperature10cm = 25,
                            SoilTemperature40cm = 26
                        },
                        new
                        {
                            Id = 4,
                            Chlorophyll = 0.12f,
                            FieldId = 7,
                            InfoTime = new DateTime(2024, 5, 16, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(7861),
                            Iron = 0.22f,
                            Nitrate = 0.32f,
                            Oxygen = 0.52f,
                            PH = 7.3f,
                            Phyto = 0.42f,
                            Phytoplankton = 0.62f,
                            Salinity = 0.82f,
                            Silicate = 0.72f,
                            SoilMoisture = 53,
                            SoilMoisture100cm = 83,
                            SoilMoisture10cm = 63,
                            SoilMoisture40cm = 73,
                            SoilTemperature = 23,
                            SoilTemperature100cm = 26,
                            SoilTemperature10cm = 24,
                            SoilTemperature40cm = 25
                        },
                        new
                        {
                            Id = 5,
                            Chlorophyll = 0.11f,
                            FieldId = 8,
                            InfoTime = new DateTime(2024, 5, 15, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(7865),
                            Iron = 0.21f,
                            Nitrate = 0.31f,
                            Oxygen = 0.51f,
                            PH = 7.4f,
                            Phyto = 0.41f,
                            Phytoplankton = 0.61f,
                            Salinity = 0.81f,
                            Silicate = 0.71f,
                            SoilMoisture = 54,
                            SoilMoisture100cm = 84,
                            SoilMoisture10cm = 64,
                            SoilMoisture40cm = 74,
                            SoilTemperature = 22,
                            SoilTemperature100cm = 25,
                            SoilTemperature10cm = 23,
                            SoilTemperature40cm = 24
                        },
                        new
                        {
                            Id = 6,
                            Chlorophyll = 0.13f,
                            FieldId = 9,
                            InfoTime = new DateTime(2024, 5, 14, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(7868),
                            Iron = 0.23f,
                            Nitrate = 0.33f,
                            Oxygen = 0.53f,
                            PH = 7.5f,
                            Phyto = 0.43f,
                            Phytoplankton = 0.63f,
                            Salinity = 0.83f,
                            Silicate = 0.73f,
                            SoilMoisture = 56,
                            SoilMoisture100cm = 86,
                            SoilMoisture10cm = 66,
                            SoilMoisture40cm = 76,
                            SoilTemperature = 21,
                            SoilTemperature100cm = 24,
                            SoilTemperature10cm = 22,
                            SoilTemperature40cm = 23
                        },
                        new
                        {
                            Id = 7,
                            Chlorophyll = 0.14f,
                            FieldId = 10,
                            InfoTime = new DateTime(2024, 5, 13, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(7872),
                            Iron = 0.24f,
                            Nitrate = 0.34f,
                            Oxygen = 0.54f,
                            PH = 7.6f,
                            Phyto = 0.44f,
                            Phytoplankton = 0.64f,
                            Salinity = 0.84f,
                            Silicate = 0.74f,
                            SoilMoisture = 57,
                            SoilMoisture100cm = 87,
                            SoilMoisture10cm = 67,
                            SoilMoisture40cm = 77,
                            SoilTemperature = 20,
                            SoilTemperature100cm = 23,
                            SoilTemperature10cm = 21,
                            SoilTemperature40cm = 22
                        },
                        new
                        {
                            Id = 8,
                            Chlorophyll = 0.16f,
                            FieldId = 11,
                            InfoTime = new DateTime(2024, 5, 12, 12, 59, 11, 38, DateTimeKind.Local).AddTicks(7875),
                            Iron = 0.26f,
                            Nitrate = 0.36f,
                            Oxygen = 0.56f,
                            PH = 7.7f,
                            Phyto = 0.46f,
                            Phytoplankton = 0.66f,
                            Salinity = 0.86f,
                            Silicate = 0.76f,
                            SoilMoisture = 58,
                            SoilMoisture100cm = 88,
                            SoilMoisture10cm = 68,
                            SoilMoisture40cm = 78,
                            SoilTemperature = 19,
                            SoilTemperature100cm = 22,
                            SoilTemperature10cm = 20,
                            SoilTemperature40cm = 21
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AMSS.Models.Crop", b =>
                {
                    b.HasOne("AMSS.Models.CropType", "CropType")
                        .WithMany("Crops")
                        .HasForeignKey("CropTypeId");

                    b.Navigation("CropType");
                });

            modelBuilder.Entity("AMSS.Models.Farm", b =>
                {
                    b.HasOne("AMSS.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("AMSS.Models.Polygon.PolygonApp", "PolygonApp")
                        .WithOne("Farm")
                        .HasForeignKey("AMSS.Models.Farm", "PolygonAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("PolygonApp");
                });

            modelBuilder.Entity("AMSS.Models.Field", b =>
                {
                    b.HasOne("AMSS.Models.Farm", "Farm")
                        .WithMany("Fields")
                        .HasForeignKey("FarmId");

                    b.HasOne("AMSS.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("AMSS.Models.Polygon.PolygonApp", "PolygonApp")
                        .WithOne("Field")
                        .HasForeignKey("AMSS.Models.Field", "PolygonAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");

                    b.Navigation("Location");

                    b.Navigation("PolygonApp");
                });

            modelBuilder.Entity("AMSS.Models.FieldCrop", b =>
                {
                    b.HasOne("AMSS.Models.Crop", "Crop")
                        .WithMany("FieldCrops")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMSS.Models.Field", "Field")
                        .WithMany("FieldCrops")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("AMSS.Models.Polygon.Position", b =>
                {
                    b.HasOne("AMSS.Models.Polygon.PolygonApp", "PolygonApp")
                        .WithMany("Positions")
                        .HasForeignKey("PolygonAppId");

                    b.Navigation("PolygonApp");
                });

            modelBuilder.Entity("AMSS.Models.SoilQuality", b =>
                {
                    b.HasOne("AMSS.Models.Field", "Field")
                        .WithOne("SoilQuality")
                        .HasForeignKey("AMSS.Models.SoilQuality", "FieldId");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AMSS.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AMSS.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AMSS.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AMSS.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMSS.Models.Crop", b =>
                {
                    b.Navigation("FieldCrops");
                });

            modelBuilder.Entity("AMSS.Models.CropType", b =>
                {
                    b.Navigation("Crops");
                });

            modelBuilder.Entity("AMSS.Models.Farm", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("AMSS.Models.Field", b =>
                {
                    b.Navigation("FieldCrops");

                    b.Navigation("SoilQuality")
                        .IsRequired();
                });

            modelBuilder.Entity("AMSS.Models.Polygon.PolygonApp", b =>
                {
                    b.Navigation("Farm")
                        .IsRequired();

                    b.Navigation("Field")
                        .IsRequired();

                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
